[package]
name = "4get"
version = "1.3.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
hyper = "0.9"
scraper = "0.4"
num_cpus = "0.2"
regex = "0.1"
threadpool = "1.3"
clap = "2"
